# coding=utf-8

metar = {
    'doc': 'A schema representing a METAR weather telegram',
    'name': 'METAR',
    'namespace': 'com.helioserv.tests',
    'type': 'record',
    'fields': [
        {"name": "station_identifier",
         "type": "string",
         "default": "NONE"},
        {"name": "day",
         "type": "int",
         "default": "NONE"},
        {"name": "hour",
         "type": "int",
         "default": "NONE"},
        {"name": "minute",
         "type": "int",
         "default": "NONE"},
        {"name": "wind_speed",
         "type": "int",
         "default": "9999"},
        {"name": "wind_direction",
         "type": "string",
         "default": "NONE"},
        {"name": "gusts",
         "type": "int",
         "default": "NONE"},
        {"name": "visibility",
         "type": "int",
         "default": "9999"},
        {"name": "weather",
         "type": "string",
         "default": "NONE"},
        {"name": "layers_aloft",
         "type": "map",
         "values": "string",
         "default": "NONE"},
        {"name": "temperature",
         "type": "string",
         "default": "NONE"},
        {"name": "dewpoint",
         "type": "string",
         "default": "NONE"},
        {"name": "altimeter_setting",
         "type": "float",
         "default": "NONE"},
        {"name": "remarks",
         "type": "string",
         "default": "NONE"}
    ]
}
